### ISSUE TITLE
Java beans for representation of a custom action and resources defined by the Dynamic API ontology

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3619]
**Is your feature request related to a problem? Please describe.**
A Java package for Object representation of resource with linked custom actions RDF is needed. 

**Describe the solution you'd like**
Java beans should be aligned with the [ontology](https://github.com/vivo-project/VIVO/issues/3617)

**Tasks**
- [X] Action
- [x] Add Java bean for Role [here](https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components) and link it with the ontology class [here](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/dynamic-api-implementation.n3). It should be linked with Action (setRole (RequiresAccess) property), and this should be used for definition who can invoke execution of the action. 
- Step 
   - [X] Operational Step
   - [x] [Conditional Step](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/ConditionalStep.java) - add hasQuestion, nextIfTrue, nextIfFalse 
- Operation
     -  Template
           - [X] N3Template  
     - [X] SPARQL Query 
     - [x] Add Java bean for SolrQuery [here](https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components) and link it with the ontology class [here](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/dynamic-api-implementation.n3) 
- [X] Parameter
     - [X] Parameter type 
- [X] [Validators](https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/validators)  
- [X] Model
- [X] Resource
- [X] RPC
- [X] HTTPMethod
- [X] CustomAction

**Additional context**
The draft version of Java beans available at https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components

The draft version of linking ontology classes and java classes available at https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/dynamic-api-implementation.n3

**Comment by chenejac** [comment]
Linked GitHub issue - https://github.com/vivo-project/VIVO/issues/3617

**Comment by chenejac** [comment]
Role class from the ontology should be added in the Java beans package. It should be linked with Action (setRole (RequiresAccess) property), and this should be used for definition who can invoke execution of the action. The creation and update of an action probably will be granted only to administrators, and it depends on setting privileges on the VIVO level for the Definition of a custom action web page.
