### ISSUE TITLE
Endpoint for running a custom action

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3622]
**Is your feature request related to a problem? Please describe.**
An endpoint capable to unpack data, recognize which dynamic action has been invoked and run it with the provided data is needed. 

**Describe the solution you'd like**
The endpoint should find rpcName as a request parameter and use that to find the action object representation in the [ActionPool](https://github.com/vivo-project/VIVO/issues/3621). Other request parameter should be loaded in a map and used as values for the certain parameters used by action steps. There should be call propagation of the _run_ method declared in [the RunnableComponents interface](https://github.com/litvinovg/Vitro/blob/dynapi/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/RunnableComponent.java)

**Tasks**
- RPCEndpoint
  - [x] Finding an action (see #3621)  
  - [x] Mapping request data to OperationData (see #3661)
  - [x] Running an action (see #3648)
  - [x] Mapping of OpearationResult to a response (see #3661). 

**Additional context**
[The Action processing flow](https://app.diagrams.net/#G1I1aKVWlSsvLOjEAI5_u1ck0ieuzSdX6y)
[RPCEndpoint](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/RPCEndpoint.java)  
[OperationData](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/OperationData.java)
[OperationResult](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/OperationResult.java)
