### ISSUE TITLE
Template classes

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3638]
**Describe the solution you'd like**
A Template class is defined in the [ontology](https://github.com/vivo-project/VIVO/issues/3617). There is one sub-type: N3Template. 
There should be [Java classes](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java) representing this ontology classes, annotated with Properties annotations for [automatic loading](https://github.com/vivo-project/VIVO/issues/3620). Also, N3Template class should implement [run method](https://github.com/vivo-project/VIVO/issues/3648) capable to run defined N3 template and provided parameters over a graph.  

**Tasks**
- N3Template
    - [X] [Ontology](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/vitro-dynamic-api.owl) 
    - [X] [Java Bean representation](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java)
    - [x] [Loading](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java#L26)
    - [x] [Execution](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java#L21)
    - [x] [Testing](https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb-staging/api/src/test/java/edu/cornell/mannlib/vitro/webapp/dynapi)

**Comment by litvinovg** [comment]
https://github.com/vivo-project/Vitro/commit/5a1e1f50a71c179379370430d2efab9d4a1a2921
