### ISSUE TITLE
SPARQL Query class

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3639]
**Describe the solution you'd like**
A SPARQL Query class is defined in the [ontology](https://github.com/vivo-project/VIVO/issues/3617). 
There should be [a Java class](https://github.com/litvinovg/Vitro/blob/dynapi/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/SPARQLQuery.java) representing this ontology class, annotated with Properties annotations for [automatic loading](https://github.com/vivo-project/VIVO/issues/3620). Also, this class should implement [run method](https://github.com/vivo-project/VIVO/issues/3648) capable to execute SPARQL  query with provided parameters over a graph.  

**Tasks**
- SPARQLQuery
    - [X] [Ontology](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/vitro-dynamic-api.owl#L443)
    - [X] [Java Bean representation](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/SPARQLQuery.java)
    - [X] [Loading](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/SPARQLQuery.java#L34)
    - [X] [Execution](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/SPARQLQuery.java#L63)
    - [x] [Testing](https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb-staging/api/src/test/java/edu/cornell/mannlib/vitro/webapp/dynapi)

**Comment by litvinovg** [comment]
https://github.com/vivo-project/Vitro/commit/5a1e1f50a71c179379370430d2efab9d4a1a2921

**Comment by litvinovg** [comment]
https://github.com/vivo-project/Vitro/pull/327
