### ISSUE TITLE
Solr Query class

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3640]
**Describe the solution you'd like**
A SolrQuery class is defined in the [ontology](https://github.com/vivo-project/VIVO/issues/3617). 
There should be [a Java class](https://github.com/litvinovg/Vitro/blob/dynapi/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components) representing this ontology class, annotated with Properties annotations for [automatic loading](https://github.com/vivo-project/VIVO/issues/3620). Also, this class should implement [run method](https://github.com/vivo-project/VIVO/issues/3648) capable to execute Solr Query with provided parameters over a Solr engine.  

**Tasks** 
- [x] SolrQuery
    - [x] [Ontology](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/vitro-dynamic-api.owl#L452)
    - [x] [Linking ontology class with implementation](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/dynamic-api-implementation.n3)
    - [x] [Java Bean representation](https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components)
    - [x] [Loading](https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components)
    - [x] [Execution](https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components)

**Comment by chenejac** [comment]
Should we support ElasticSearch as well?
