### ISSUE TITLE
Execution of an action

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3648]
**Describe the solution you'd like**
An action described in [RDF](https://github.com/vivo-project/VIVO/issues/3617) and loaded [in-memory Java representation](https://github.com/vivo-project/VIVO/issues/3620) should be executed. All [components](https://github.com/vivo-project/VIVO/issues/3619) which implement [RunnableComponent](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/RunnableComponent.java) Interface should implement run method. The run method use OperationData as an input, and produce OperationResult. 

**Tasks**
- [ ] Define run method for 
    - [X] Action 
    - [ ] [Steps](https://github.com/vivo-project/VIVO/issues/3636)
    - [ ] [N3Template](https://github.com/vivo-project/VIVO/issues/3638)
    - [ ] [SPARQLQuery](https://github.com/vivo-project/VIVO/issues/3639)
    - [ ] [SolrQuery](https://github.com/vivo-project/VIVO/issues/3640)  

**Additional context**
https://github.com/vivo-project/Vitro/tree/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components
