### ISSUE TITLE
Assigning role for a dynamic action

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3650]
**Describe the solution you'd like**
Assigning role for definition of security aspects and authorizing execution of a dynamic action should be added. It should be part of the [Dynamic API ontology](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/dynamic-api-implementation.n3). 

**Tasks**
- Role
    - [X] Ontology
    - [x] Java Bean representation
    - [x] Loading 
    - [x] [Linking with implementation](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/dynamic-api-implementation.n3)
    - [x] [Enumeration of roles](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/abox/filegraph/dynamic-api-individuals.n3)
- Action
    - [x]  Linking with role
         - [X] Ontology
         - [x] Java representation
