### ISSUE TITLE
Define Property annotations for setters in JavaBeans

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3660]
**Tasks**
- [X] Define Property annotations for setters in JavaBeans
     - [x] N3Template - [addRequiredParameter](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java#L27) and [addProvidedParameter](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java#L33)
     - [x] ConditionalStep - setQuestion (hasQuestion), setNextIfTrue (nextIfTrue), setNextIfFalse (nextIfFalse)
