### ISSUE TITLE
Implementation of the REST endpoint

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3667]
**Tasks**
- [x] #3668
- [x] Find a resource in ResourcePool by using parameters in path (see #3651) 
- [x] Find an action based on HTTP method and resource (see #3621)
- [x] Pass [OperationData](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/OperationData.java) to action and [run action](#3648) 
- [x] Convert [OperationResult](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/OperationResult.java) to HTTP response (JSON should be used)
