### ISSUE TITLE
REST Endpoint Documentation

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3670]
**Tasks**
- [x] [wiki](https://wiki.lyrasis.org/display/VIVODOC112x/VIVO+Dynamic+API)
- [x] [Manual Writing Generic OpenAPI specification for REST endpoint](https://editor.swagger.io/?url=https://gist.githubusercontent.com/wwelling/fa140a474cce0f0540dce7491baec6eb/raw/547d3f495e1561318afcae5df31824c682753abe/vivo-dynamic-api.yaml) 
- [x] Generating a resource specific OpenAPI specification (for instance, for the researcher resource, GET /api/rest/1.0/researcher/{research_uri}, POST, PUT, DELETE, customRESTaction)

**Comment by chenejac** [comment]
Maybe we can also consider making a RESTContract described by using Markdown files. Anyway, we need to document endpoint in some human readable way (wiki, markdown, or something similar).
