### ISSUE TITLE
RPC Endpoint documentation

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3677]
**Tasks**
- [x] [wiki](https://wiki.lyrasis.org/display/VIVODOC112x/VIVO+Dynamic+API)
- [x] [Manual Writing Generic OpenAPI specification for RPC endpoint](https://editor.swagger.io/?url=https://gist.githubusercontent.com/wwelling/fa140a474cce0f0540dce7491baec6eb/raw/5de47f592abafb2c55963e077068382799aaa2ff/vivo-dynamic-api.yaml) 
- [x] Generating an action specific OpenAPI specification (with specifying requested JSON structure and response )
